# Site settings
title: School of Computer Engineering-Iran University of Science and Technology
course_name: Advanced Programming
course_description: "The purpose of this lesson is to present different ways of producing a quality program. In this regard, after the cover
a bottom-up design approach to problem-solving, providing students with object-oriented programming concepts as a tool for
complexity management is introduced in medium to large applications. During the lesson, performance properly
programs, tests, and debugging are focused on techniques such as unit testing, assertions, and
pre- and post-conditions are fulfilled. The lesson will focus on methods rather than the structures of a language
Special programming. This lesson can be taught in any common object-oriented programming language such as Java or C ++."
course_semester: "Fall 2019"
description: |
    Instructor: Dr.Marzieh Malekimajd

message: #Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/ap98" # the subpath of your site, e.g. /blog/
url: "http://parmiida.github.io/ap98" # the base hostname & protocol for your site
syllabus: http://parmiida.github.io/ap98/syllabus/
githubdir: 

# Author/user information

authorurl: "http://parmiida.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
